require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - spec/dummy/db/schema.rb
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - spec/dummy/db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/migrate/*.rb

RSpec/FilePath:
  CustomTransform:
    IndieAuth: indieauth

Style/Documentation:
  Exclude:
    - spec/dummy/**/*.rb
